version: '3.9'

services:
  # PHP Service
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  # Nginx Service
  app:
    image: nginx:latest
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    ports:
      - "3000:80"
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge